site_name: API PochocloCritics v2.0
nav:
  - Home: index.md
  - Usuarios: usuarios.md
  - Moderadores: moderadores.md
  - Actores: actores.md
  - Directores: directores.md
  - Peliculas: peliculas.md
  - Preferencias: preferencias.md
  - Reseñas: reseñas.md

theme: readthedocs
